const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'src/screens/NewInvoiceScreen.js');
let content = fs.readFileSync(filePath, 'utf8');

const anchor = 'const styles = StyleSheet.create({';
const idx = content.indexOf(anchor);

if (idx === -1) {
    console.error('Could not find styles definition');
    process.exit(1);
}

// Slice out the top part up to the styles definition
const newContent = content.slice(0, idx) + `const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 24,
        paddingTop: 60,
        paddingBottom: 20,
        backgroundColor: 'rgba(10, 10, 12, 0.8)',
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255,255,255,0.05)',
        zIndex: 10,
    },
    closeBtn: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(255,255,255,0.05)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerTitle: {
        color: COLORS.text,
        fontSize: 24,
        fontWeight: '700',
        letterSpacing: -0.5,
    },
    scrollContent: {
        padding: 24,
        paddingBottom: 150,
    },
    inputGroup: {
        marginBottom: 24,
    },
    label: {
        color: COLORS.textSecondary,
        fontSize: 12,
        fontWeight: '600',
        letterSpacing: 1,
        marginBottom: 8,
        marginLeft: 4,
    },
    labelRowItems: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.03)',
        borderRadius: 16,
        paddingHorizontal: 16,
        height: 60,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.05)',
    },
    iconBox: {
        width: 36,
        height: 36,
        borderRadius: 12,
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    input: {
        flex: 1,
        color: COLORS.text,
        fontSize: 16,
        fontWeight: '500',
    },
    inputText: {
        flex: 1,
        color: COLORS.text,
        fontSize: 16,
        fontWeight: '500',
    },
    addSmallBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(16, 185, 129, 0.1)',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 12,
        gap: 4,
    },
    addSmallText: {
        color: COLORS.success,
        fontSize: 13,
        fontWeight: '600',
    },
    emptyItemsBox: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        height: 100,
        backgroundColor: 'rgba(255,255,255,0.02)',
        borderRadius: 16,
        borderWidth: 1,
        borderStyle: 'dashed',
        borderColor: 'rgba(255,255,255,0.1)',
        gap: 12,
    },
    emptyText: {
        color: COLORS.textSecondary,
        fontSize: 15,
    },
    itemWrapper: {
        marginBottom: 12,
    },
    itemGlassCard: {
        backgroundColor: 'rgba(255,255,255,0.03)',
        borderRadius: 20,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.05)',
        padding: 16,
    },
    itemHeader: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        marginBottom: 16,
    },
    itemNameText: {
        color: COLORS.text,
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 4,
    },
    itemSkuText: {
        color: COLORS.textSecondary,
        fontSize: 13,
    },
    deleteIconButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: 'rgba(239, 68, 68, 0.1)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    itemFooter: {
        borderTopWidth: 1,
        borderTopColor: 'rgba(255,255,255,0.05)',
        paddingTop: 16,
    },
    footerInputs: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 12,
    },
    miniLabel: {
        color: COLORS.textSecondary,
        fontSize: 11,
        fontWeight: '600',
        marginBottom: 6,
        letterSpacing: 0.5,
    },
    miniQtyContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.2)',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.05)',
        height: 44,
    },
    qtyBtn: {
        width: 44,
        height: 44,
        alignItems: 'center',
        justifyContent: 'center',
    },
    miniInput: {
        width: 50,
        color: COLORS.text,
        fontSize: 16,
        fontWeight: '600',
        textAlign: 'center',
        paddingVertical: 0,
    },
    miniPriceContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.2)',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.05)',
        height: 44,
        paddingHorizontal: 12,
        flex: 1,
        minWidth: 120,
    },
    priceSymbol: {
        color: COLORS.textSecondary,
        fontSize: 16,
        fontWeight: '600',
        marginRight: 4,
    },
    miniPriceInput: {
        flex: 1,
        color: COLORS.text,
        fontSize: 16,
        fontWeight: '600',
        paddingVertical: 0,
    },
    glassPanel: {
        backgroundColor: 'rgba(255,255,255,0.03)',
        borderRadius: 20,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.05)',
        padding: 16,
    },
    toggleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    toggleLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    toggleText: {
        color: COLORS.textSecondary,
        fontSize: 15,
        fontWeight: '500',
    },
    divider: {
        height: 1,
        backgroundColor: 'rgba(255,255,255,0.05)',
        marginVertical: 16,
    },
    smallInputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.2)',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.05)',
        paddingHorizontal: 12,
        height: 36,
        width: 80,
    },
    smallInput: {
        flex: 1,
        color: COLORS.text,
        fontSize: 14,
        fontWeight: '600',
        textAlign: 'center',
        paddingVertical: 0,
    },
    smallInputSuffix: {
        color: COLORS.textSecondary,
        fontSize: 14,
        marginLeft: 2,
    },
    discountExpanded: {
        marginTop: 16,
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: 'rgba(255,255,255,0.05)',
        gap: 12,
    },
    discountTypeSelector: {
        flexDirection: 'row',
        backgroundColor: 'rgba(0,0,0,0.2)',
        borderRadius: 12,
        padding: 4,
    },
    typeBtn: {
        flex: 1,
        paddingVertical: 8,
        alignItems: 'center',
        borderRadius: 8,
    },
    typeBtnActive: {
        backgroundColor: 'rgba(255,255,255,0.1)',
    },
    typeBtnText: {
        color: COLORS.textSecondary,
        fontSize: 13,
        fontWeight: '500',
    },
    typeBtnTextActive: {
        color: COLORS.text,
        fontWeight: '600',
    },
    summaryPanel: {
        backgroundColor: 'rgba(16, 185, 129, 0.05)',
        borderRadius: 20,
        borderWidth: 1,
        borderColor: 'rgba(16, 185, 129, 0.1)',
        padding: 20,
        gap: 12,
    },
    summaryLine: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    summaryLineLabel: {
        color: COLORS.textSecondary,
        fontSize: 14,
    },
    summaryLineValue: {
        color: COLORS.text,
        fontSize: 15,
        fontWeight: '500',
    },
    summaryDivider: {
        height: 1,
        backgroundColor: 'rgba(16, 185, 129, 0.1)',
        marginVertical: 4,
    },
    summaryTotalLine: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        marginTop: 4,
    },
    summaryTotalLabel: {
        color: COLORS.text,
        fontSize: 16,
        fontWeight: '600',
    },
    summaryTotalValue: {
        color: COLORS.success,
        fontSize: 28,
        fontWeight: '700',
        letterSpacing: -0.5,
    },
    footer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        flexDirection: 'row',
        padding: 24,
        paddingTop: 16,
        paddingBottom: Platform.OS === 'ios' ? 34 : 24,
        backgroundColor: 'rgba(10, 10, 12, 0.95)',
        borderTopWidth: 1,
        borderTopColor: 'rgba(255,255,255,0.05)',
        gap: 12,
    },
    btnSecondary: {
        flex: 1,
        height: 56,
        backgroundColor: 'rgba(255,255,255,0.05)',
        borderRadius: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
    },
    btnSecondaryText: {
        color: COLORS.text,
        fontSize: 16,
        fontWeight: '600',
    },
    btnPrimary: {
        flex: 2,
        height: 56,
        backgroundColor: COLORS.success,
        borderRadius: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
    },
    btnPrimaryText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '700',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.6)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: '#0f172a',
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        padding: 24,
        paddingBottom: Platform.OS === 'ios' ? 34 : 24,
        maxHeight: '80%',
        borderTopWidth: 1,
        borderColor: 'rgba(255,255,255,0.05)',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: COLORS.text,
    },
    closeModalBtn: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(255,255,255,0.05)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalSearchBox: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255,255,255,0.05)',
        borderRadius: 16,
        paddingHorizontal: 16,
        height: 50,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.05)',
        marginBottom: 20,
    },
    modalInput: {
        flex: 1,
        color: COLORS.text,
        marginLeft: 12,
        fontSize: 15,
    },
    modalItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255,255,255,0.05)',
    },
    modalItemText: {
        color: COLORS.text,
        fontSize: 16,
        fontWeight: '500',
        marginBottom: 2,
    },
    modalItemSub: {
        color: COLORS.textSecondary,
        fontSize: 13,
    }
});
`;

fs.writeFileSync(filePath, newContent, 'utf8');
console.log('Successfully updated styles!');
